version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: missions_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5437:5437"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=postgresql://admin:1234@localhost:5437/missions_db

volumes:
  db_data: